label var SbjNum "Questionário "
label var Seq "Sequência "
label var Nome_Municipio "Município "
label var QUEST "Questionário "
label var Sexo "Sexo "
label var Idade "Idade "
label var IDAD "Idade (faixas) "
label var inst "ESCOLARIDADE "
label var OCUPA "OCUPAÇÃO) O(A) sr(a) trabalha atualmente? Tem alguma fonte de renda, trabalho informal, mesmo que não seja registrado? "
label var P1 "P.01) Qual foi a última série que o(a) sr(a) completou com aprovação? "
label var P1A "P.01A) Qual foi a última série que o(a) sr(a) completou com aprovação? "
label var P3 "P.03) O(A) sr(a) ainda está estudando? "
label var P4 "P.04) Com que idade o(a) sr(a) completou a última série cursada? "
label var P501 "P.05A) Para cada nível de escolaridade completado, em que rede o(a) sr(a) cursou a maior parte de sua instrução? Fundamental (1ª a 8ª série ou 1º a 9º ano) "
label var P502 "P.05B) Para cada nível de escolaridade completado, em que rede o(a) sr(a) cursou a maior parte de sua instrução? Ensino Médio (1º a 3º ano) "
label var P503 "P.05C) Para cada nível de escolaridade completado, em que rede o(a) sr(a) cursou a maior parte de sua instrução? Ensino Superior "
label var P504 "P.05D) Para cada nível de escolaridade completado, em que rede o(a) sr(a) cursou a maior parte de sua instrução? Pós-Graduação/ Mestrado/ Doutorado "
label var P601 "P.06) Gostaria de saber qual é a escolaridade do seu pai / do responsável do sexo masculino que o(a) criou? (Espontânea) "
label var P602 "P.06) Gostaria de saber qual é a escolaridade do seu pai / do responsável do sexo masculino que o(a) criou? (Espontânea) "
label var P6A "P.06A) Gostaria de saber qual é a escolaridade do seu outro pai / do outro responsável do sexo masculino que o(a) criou? (Espontânea) "
label var P701 "P.07) Qual é a escolaridade da sua mãe / da responsável do sexo feminino que o(a) criou? (Espontânea) "
label var P702 "P.07) Qual é a escolaridade da sua mãe / da responsável do sexo feminino que o(a) criou? (Espontânea) "
label var P7A "P.07A) Gostaria de saber qual é a escolaridade da sua outra mãe / da outra responsável do sexo feminino que o(a) criou? "
label var P8 "P.08) Sabe ler e escrever um bilhete simples? "
label var P901 "P.09A) Nos últimos 3 meses, o (a) sr(a) leu livros didáticos indicados pela escola, ou seja, livros utilizados nas matérias do seu curso? "
label var P902 "P.09B) Nos últimos 3 meses, o (a) sr(a) leu livros de literatura indicados pela escola, como contos, romances ou poesias? "
label var P903 "P.09C) Nos últimos 3 meses, o (a) sr(a) leu livros de trabalho, técnicos, para formação profissional? "
label var P904 "P.09D) Nos últimos 3 meses, o (a) sr(a) leu livros de literatura por vontade própria, como contos, romances ou poesias? "
label var P905 "P.09E) Nos últimos 3 meses, o (a) sr(a) leu livros em geral, de outros tipos? "
label var P906 "P.09F) Nos últimos 3 meses, o (a) sr(a) leu gibis ou histórias em quadrinhos? "
label var P907 "P.09G) Nos últimos 3 meses, o (a) sr(a) leu revistas? "
label var P908 "P.09H) Nos últimos 3 meses, o (a) sr(a) leu jornais? "
label var P909 "P.09I) Nos últimos 3 meses, o (a) sr(a) leu textos de trabalho? "
label var P910 "P.09J) Nos últimos 3 meses, o (a) sr(a) leu textos escolares? "
label var P911 "P.09K) Nos últimos 3 meses, o (a) sr(a) leu livros em braille? "
label var P912 "P.09L) Nos últimos 3 meses, o (a) sr(a) leu livros religiosos, como a Bíblia? "
label var P913 "P.09M) Nos últimos 3 meses, o (a) sr(a) leu blogs ou outros textos na Internet? "
label var P914 "P.09N) Nos últimos 3 meses, o (a) sr(a) ouviu audiolivros? "
label var P10 "P.10) Dos livros que o(a) sr(a) leu nos últimos 3 meses, o(a) sr(a) diria que: "
label var P10A "P.10A) Dos gibis, revistas, jornais ou textos em geral que o(a) sr(a) leu nos últimos 3 meses, o(a) sr(a) diria que: "
label var P1101 "P.11A) Para cada finalidade, com que frequência o(a) sr(a) costuma ler livros, jornais, revistas etc., impressos ou digitais? O(A) sr(a) costuma ler por prazer / por gosto pela leitura: "
label var P1102 "P.11B) Para cada finalidade, com que frequência o(a) sr(a) costuma ler livros, jornais, revistas etc., impressos ou digitais? O(A) sr(a) costuma ler para aprender / estudar: "
label var P1103 "P.11C) Para cada finalidade, com que frequência o(a) sr(a) costuma ler livros, jornais, revistas etc., impressos ou digitais? O(A) sr(a) costuma ler para se informar sobre assuntos de seu interesse pessoal: "
label var P1104 "P.11D) Para cada finalidade, com que frequência o(a) sr(a) costuma ler livros, jornais, revistas etc., impressos ou digitais? O(A) sr(a) costuma ler para se informar sobre assuntos de seu interesse profissional: "
label var P1105 "P.11E) Para cada finalidade, com que frequência o(a) sr(a) costuma ler livros, jornais, revistas etc., impressos ou digitais? O(A) sr(a) costuma ler para se aperfeiçoar na vida e melhorar valores e comportamento: "
label var P1106 "P.11F) Para cada finalidade, com que frequência o(a) sr(a) costuma ler livros, jornais, revistas etc., impressos ou digitais? O(A) sr(a) costuma ler para fazer orações, acompanhar cultos e rituais religiosos (inclui leitura de Bíblia): "
label var P1107 "P.11G) Para cada finalidade, com que frequência o(a) sr(a) costuma ler livros, jornais, revistas etc., impressos ou digitais? O(A) sr(a) costuma ler para se distrair / passar o tempo : "
label var P1108 "P.11H) Para cada finalidade, com que frequência o(a) sr(a) costuma ler livros, jornais, revistas etc., impressos ou digitais? O(A) sr(a) costuma ler por outra razão: "
label var P1108_out "P.11) Outros "
label var P1201 "P.12) Quais são as duas pessoas que mais influenciaram ou incentivaram sua disposição para a leitura? "
label var P1202 "P.12) Quais são as duas pessoas que mais influenciaram ou incentivaram sua disposição para a leitura? "
label var P1301 "P.13A) Os livros impressos ou digitais que o(a) sr(a) costuma ler são comprados em lojas físicas ou pela Internet? "
label var P1302 "P.13B) Os livros impressos ou digitais que o(a) sr(a) costuma ler são fotocopiados, xerocados ou digitalizados? "
label var P1303 "P.13C) Os livros impressos ou digitais que o(a) sr(a) costuma ler são presenteados? "
label var P1304 "P.13D) Os livros impressos ou digitais que o(a) sr(a) costuma ler são retirados ou lidos em bibliotecas ou espaços de leitura? "
label var P1305 "P.13E) Os livros impressos ou digitais que o(a) sr(a) costuma ler são emprestados por outras pessoas, como colegas e familiares? "
label var P1306 "P.13F) Os livros impressos ou digitais que o(a) sr(a) costuma ler são distribuídos pelo governo ou pelas escolas? "
label var P1307 "P.13G) Os livros impressos ou digitais que o(a) sr(a) costuma ler são doados / disponibilizados em locais públicos? "
label var P1308 "P.13H) Os livros impressos ou digitais que o(a) sr(a) costuma ler são acessados pela Internet? "
label var P1309 "P.13I) Não costuma ler livros (Espontânea) "
label var P1401 "P.14A) Onde o(a) sr(a) costuma ir para ler ou pegar emprestado livros e outros materiais de leitura, tanto no formato impresso quanto digital? O(A) sr(a) costuma ir à biblioteca pública / biblioteca comunitária / espaços de leitura? "
label var P1402 "P.14B) Onde o(a) sr(a) costuma ir para ler ou pegar emprestado livros e outros materiais de leitura, tanto no formato impresso quanto digital? O(A) sr(a) costuma ir à biblioteca da escola / da faculdade? "
label var P1403 "P.14C) Onde o(a) sr(a) costuma ir para ler ou pegar emprestado livros e outros materiais de leitura, tanto no formato impresso quanto digital? O(A) sr(a) costuma ir ao local de trabalho? "
label var P1404 "P.14D) Onde o(a) sr(a) costuma ir para ler ou pegar emprestado livros e outros materiais de leitura, tanto no formato impresso quanto digital? O(A) sr(a) costuma ir ao clube? "
label var P1405 "P.14E) Onde o(a) sr(a) costuma ir para ler ou pegar emprestado livros e outros materiais de leitura, tanto no formato impresso quanto digital? O(A) sr(a) costuma ir à igreja? "
label var P1406 "P.14F) Onde o(a) sr(a) costuma ir para ler ou pegar emprestado livros e outros materiais de leitura, tanto no formato impresso quanto digital? O(A) sr(a) costuma ir às associações de bairro? "
label var P1407 "P.14G) Onde o(a) sr(a) costuma ir para ler ou pegar emprestado livros e outros materiais de leitura, tanto no formato impresso quanto digital? O(A) sr(a) costuma ir ao sindicato? "
label var P1408 "P.14H) Onde o(a) sr(a) costuma ir para ler ou pegar emprestado livros e outros materiais de leitura, tanto no formato impresso quanto digital? O(A) sr(a) costuma ir à biblioteca volante (ex.: ônibus)? "
label var P1409 "P.14I) Onde o(a) sr(a) costuma ir para ler ou pegar emprestado livros e outros materiais de leitura, tanto no formato impresso quanto digital? O(A) sr(a) costuma ir aos quiosques em praças ou locais públicos? "
label var P1410 "P.14J) Onde o(a) sr(a) costuma ir para ler ou pegar emprestado livros e outros materiais de leitura, tanto no formato impresso quanto digital? O(A) sr(a) costuma ir à outros lugares "
label var P1411 "P.14K) Não costuma ir a locais para ler ou pegar livros emprestados (Espontânea) "
label var p1410_out "P.14) Outros "
label var P14A01 "P.14A.1) Quais dos fatores abaixo faria com que o(a) sr(a) lesse livros de literatura (contos, romances ou poesias) com maior frequência? Ter alguém que ajude o(a) sr(a) a escolher bons livros para ler "
label var P14A02 "P.14A.2) Quais dos fatores abaixo faria com que o(a) sr(a) lesse livros de literatura (contos, romances ou poesias) com maior frequência? Ter com quem conversar sobre um livro que está lendo "
label var P14A03 "P.14A.3) Quais dos fatores abaixo faria com que o(a) sr(a) lesse livros de literatura (contos, romances ou poesias) com maior frequência? Ter alguém que possa ler para o(a) sr(a) "
label var P14A04 "P.14A.4) Quais dos fatores abaixo faria com que o(a) sr(a) lesse livros de literatura (contos, romances ou poesias) com maior frequência? Fazer parte de um grupo onde todos leem juntos (rodas de leitura) "
label var P14A05 "P.14A.5) Quais dos fatores abaixo faria com que o(a) sr(a) lesse livros de literatura (contos, romances ou poesias) com maior frequência? Ler para outra pessoa "
label var P14A06 "P.14A.6) Quais dos fatores abaixo faria com que o(a) sr(a) lesse livros de literatura (contos, romances ou poesias) com maior frequência? Ter bibliotecas ou espaços de leitura mais próximos de casa ou do trabalho "
label var P14A07 "P.14A.7) Quais dos fatores abaixo faria com que o(a) sr(a) lesse livros de literatura (contos, romances ou poesias) com maior frequência? Ter mais recursos para comprar livros "
label var P14A08 "P.14A.8) Quais dos fatores abaixo faria com que o(a) sr(a) lesse livros de literatura (contos, romances ou poesias) com maior frequência? Ter acesso a livros online "
label var P14A09 "P.14A.9) Quais dos fatores abaixo faria com que o(a) sr(a) lesse livros de literatura (contos, romances ou poesias) com maior frequência? Ter mais tempo "
label var P14A10 "P.14A.10) Quais dos fatores abaixo faria com que o(a) sr(a) lesse livros de literatura (contos, romances ou poesias) com maior frequência? Outros fatores "
label var P14A11 "P.14A.11) Quais dos fatores abaixo faria com que o(a) sr(a) lesse livros de literatura (contos, romances ou poesias) com maior frequência? Nada me faria ler com mais frequência (Espontânea) "
label var p14a10_out "P.14A) Outros "
label var P1501 "P.15A) Quando o(a) sr(a) utilizou televisão com acesso à Internet (smart TV) pela última vez? "
label var P1502 "P.15B) Quando o(a) sr(a) utilizou computador de mesa pela última vez? "
label var P1503 "P.15C) Quando o(a) sr(a) utilizou notebook pela última vez? "
label var P1504 "P.15D) Quando o(a) sr(a) utilizou telefone celular pela última vez? "
label var P1505 "P.15E) Quando o(a) sr(a) utilizou tablet pela última vez? "
label var P1506 "P.15F) Quando o(a) sr(a) utilizou leitor de livros digitais (e-books) pela última vez? "
label var P1507 "P.15G) Quando o(a) sr(a) utilizou videogame pela última vez? "
label var P1601 "P.16A) Qual o seu grau de dificuldade para utilizar televisão com acesso à Internet (smart TV)? "
label var P1602 "P.16B) Qual o seu grau de dificuldade para utilizar computador de mesa? "
label var P1603 "P.16C) Qual o seu grau de dificuldade para utilizar notebook? "
label var P1604 "P.16D) Qual o seu grau de dificuldade para utilizar telefone celular? "
label var P1605 "P.16E) Qual o seu grau de dificuldade para utilizar tablet? "
label var P1606 "P.16F) Qual o seu grau de dificuldade para utilizar leitor de livros digitais (e-books)? "
label var P1607 "P.16G) Qual o seu grau de dificuldade para utilizar videogame? "
label var P17 "P.17) O(A) sr(a) usou a Internet nos últimos 3 meses? "
label var P1801 "P.18A) Para cada aparelho, por favor diga se o(a) sr(a) usa a Internet em cada um deles. O(A) sr(a) usa, já usou e não usa mais ou nunca usou a Internet na televisão com acesso à Internet (smart TV)? "
label var P1802 "P.18B) Para cada aparelho, por favor diga se o(a) sr(a) usa a Internet em cada um deles. O(A) sr(a) usa, já usou e não usa mais ou nunca usou a Internet no computador de mesa? "
label var P1803 "P.18C) Para cada aparelho, por favor diga se o(a) sr(a) usa a Internet em cada um deles. O(A) sr(a) usa, já usou e não usa mais ou nunca usou a Internet no notebook? "
label var P1804 "P.18D) Para cada aparelho, por favor diga se o(a) sr(a) usa a Internet em cada um deles. O(A) sr(a) usa, já usou e não usa mais ou nunca usou a Internet no telefone celular? "
label var P1805 "P.18E) Para cada aparelho, por favor diga se o(a) sr(a) usa a Internet em cada um deles. O(A) sr(a) usa, já usou e não usa mais ou nunca usou a Internet no tablet? "
label var P1806 "P.18F) Para cada aparelho, por favor diga se o(a) sr(a) usa a Internet em cada um deles. O(A) sr(a) usa, já usou e não usa mais ou nunca usou a Internet no leitor de livros digitais (e-books)? "
label var P1807 "P.18G) Para cada aparelho, por favor diga se o(a) sr(a) usa a Internet em cada um deles. O(A) sr(a) usa, já usou e não usa mais ou nunca usou a Internet no videogame? "
label var P1808 "P.18H) Para cada aparelho, por favor diga se o(a) sr(a) usa a Internet em cada um deles. O(A) sr(a) usa, já usou e não usa mais ou nunca usou a Internet em outro aparelho? "
label var p1808_out "P.18) Outros "
label var P19 "P.19) Em média, com que frequência o(a) sr(a) usou a internet  nos últimos 3 meses? "
label var P2101 "P.21A) O(A) sr(a) tem Facebook? "
label var P2102 "P.21B) O(A) sr(a) tem Instagram? "
label var P2103 "P.21C) O(A) sr(a) tem Twitter? "
label var P2104 "P.21D) O(A) sr(a) tem Whatsapp? "
label var P2105 "P.21E) O(A) sr(a) tem Skype? "
label var P2106 "P.21F) O(A) sr(a) tem Snapchat? "
label var P21A01 "P.21A.1) No Facebook o(a) sr(a) envia mensagens escritas? "
label var P21A02 "P.21A.2) No Facebook o(a) sr(a) envia mensagens de áudio? "
label var P21A03 "P.21A.3) No Facebook o(a) sr(a) envia mensagens com imagens e vídeos? "
label var P21A04 "P.21A.4) No Facebook o(a) sr(a) conversa por chamadas de voz ou vídeo? "
label var P21A05 "P.21A.5) No Facebook o(a) sr(a) lê mensagens escritas? "
label var P21A06 "P.21A.6) No Facebook o(a) sr(a) ouve áudios? "
label var P21A07 "P.21A.7) No Facebook o(a) sr(a) vê imagens e vídeos? "
label var P21A08 "P.21A.8) No Facebook o(a) sr(a) curte publicações? "
label var P21A09 "P.21A.9) No Facebook o(a) sr(a) escreve comentários em publicações? "
label var P21A10 "P.21A.10) No Facebook o(a) sr(a) utiliza carinhas ou figurinhas para comentar? "
label var P21A11 "P.21A.11) No Facebook o(a) sr(a) marca pessoas? "
label var P21A12 "P.21A.12) No Facebook o(a) sr(a) compartilha textos que outras pessoas postaram? "
label var P21A13 "P.21A.13) No Facebook o(a) sr(a) compartilha imagens ou vídeos que outras pessoas postaram? "
label var P21A14 "P.21A.14) No Facebook o(a) sr(a) publica textos que o(a) sr(a) escreveu? "
label var P21A15 "P.21A.15) No Facebook o(a) sr(a) publica imagens ou vídeos que o(a) sr(a) fez? "
label var P21A16 "P.21A.16) No Facebook o(a) sr(a) participa de grupos? "
label var P21A17 "P.21A.17) No Facebook o(a) sr(a) confirma presença ou interesse em eventos? "
label var P21A18 "P.21A.18) No Facebook o(a) sr(a) cria eventos? "
label var P21B01 "P.21B.1) No Whatsapp o(a) sr(a) envia mensagens escritas? "
label var P21B02 "P.21B.2) No Whatsapp o(a) sr(a) envia carinhas? "
label var P21B03 "P.21B.3) No Whatsapp o(a) sr(a) envia mensagens de áudios? "
label var P21B04 "P.21B.4) No Whatsapp o(a) sr(a) envia mensagens com imagens e vídeos? "
label var P21B05 "P.21B.5) No Whatsapp o(a) sr(a) conversa por chamadas de voz ou vídeo? "
label var P21B06 "P.21B.6) No Whatsapp o(a) sr(a) lê mensagens escritas? "
label var P21B07 "P.21B.7) No Whatsapp o(a) sr(a) ouve áudios? "
label var P21B08 "P.21B.8) No Whatsapp o(a) sr(a) vê imagens e vídeos? "
label var P21B09 "P.21B.9) No Whatsapp o(a) sr(a) compartilha textos que outras pessoas enviaram? "
label var P21B10 "P.21B.10) No Whatsapp o(a) sr(a) compartilha imagens ou vídeos que outras pessoas enviaram? "
label var P21B11 "P.21B.11) No Whatsapp o(a) sr(a) participa de grupos? "
label var P2201 "P.22A) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) enviou e recebeu e-mails "
label var P2202 "P.22B) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) acessou blogs "
label var P2203 "P.22C) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) procurou informações sobre produtos e serviços "
label var P2204 "P.22D) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) procurou informações relacionadas à saúde ou a serviços de saúde "
label var P2205 "P.22E) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) procurou informações sobre viagens e acomodações "
label var P2206 "P.22F) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) procurou informações em sites de enciclopédias / dicionários digitais, como  Wikipédia "
label var P2207 "P.22G) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) fez pesquisa de preços por meio de ferramentas de busca (Buscapé, Bondfaro etc.) "
label var P2208 "P.22H) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) fez compras na Internet "
label var P2209 "P.22I) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) procurou emprego ou enviou currículos "
label var P2210 "P.22J) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) fez consultas, pagamentos ou outras transações financeiras "
label var P22A01 "P.22A.1) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) obteve informações em sites de órgãos do governo / órgãos públicos? "
label var P22A02 "P.22A.2) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) preencheu formulários ou interagiu com órgãos do governo / órgãos públicos? "
label var P22A03 "P.22A.3) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) escreveu sugestões ou opiniões em fóruns ou consultas públicas na Internet? "
label var P22A04 "P.22A.4) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) participou de votações ou enquetes na Internet? "
label var P22A05 "P.22A.5) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) assinou petições ou abaixo-assinados na Internet em sites ou aplicativos como o Avaaz? "
label var P22B01 "P.22B.1) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) assistiu aulas (gravadas ou ao vivo) / palestras como TED Talks ou Khan Academy? "
label var P22B02 "P.22B.2) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) realizou pesquisas para fins de estudo? "
label var P22B03 "P.22B.3) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) acompanhou fóruns, listas e/ou grupos de discussão relacionados ao estudo? "
label var P22B04 "P.22B.4) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) publicou conteúdos em fóruns, listas e/ou grupos de discussão relacionados ao estudo (acadêmico / profissional / pessoal)? "
label var P22B05 "P.22B.5) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) fez cursos a distância / cursos livres (acadêmico / profissional / pessoal)? "
label var P22B06 "P.22B.6) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) realizou testes, provas e outros simulados? "
label var P22B07 "P.22B.7) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) acessou sites especializados em conteúdos educacionais (acadêmico / profissional / pessoal)? "
label var P22C01 "P.22C.1) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) assistiu a programas de TV pela Internet "
label var P22C02 "P.22C.2) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) ouviu programas de rádio pela Internet "
label var P22C03 "P.22C.3) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) assistiu a vídeos no Youtube "
label var P22C04 "P.22C.4) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) assistiu a filmes ou séries no Netflix "
label var P22C05 "P.22C.5) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) ouviu músicas "
label var P22C06 "P.22C.6) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) assistiu vídeos para aprender ou ver dicas sobre coisas que o(a) sr(a) não sabe "
label var P22C07 "P.22C.7) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) postou vídeos que o(a) sr(a) mesmo fez "
label var P22C08 "P.22C.8) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) leu jornais, revistas ou notícias pela Internet "
label var P22C09 "P.22C.9) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) leu artigos, contos ou romances na Internet "
label var P22C10 "P.22C.10) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) jogou jogos na Internet "
label var P22C11 "P.22C.11) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) baixou ou fez o download de filmes, de músicas, de jogos e/ou de livros ou outros conteúdos "
label var P22C12 "P.22C.12) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) produziu conteúdos para plataformas colaborativas como Wikipédia "
label var P22C13 "P.22C.13) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) usou serviços de taxi ou motoristas particulares como Uber ou 99 Taxis "
label var P22C14 "P.22C.14) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) usou mapas como Google Maps ou Waze "
label var P22C15 "P.22C.15) Quais das seguintes atividades o(a) sr(a) realizou na Internet nos últimos 3 meses? O(A) sr(a) respondeu pesquisas pela Internet "
label var P2301 "P.23A) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. O acesso às redes sociais me deixa bem informado sobre muitos assuntos "
label var P2302 "P.23B) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. Depois que comecei a usar a internet, passei a ler e escrever mais "
label var P2303 "P.23C) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. As informações que aparecem na Internet são sempre confiáveis "
label var P2304 "P.23D) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. A principal razão para eu estar nas redes sociais é conhecer novas pessoas "
label var P2305 "P.23E) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. Nas redes sociais falo apenas com pessoas que conheço pessoalmente "
label var P2306 "P.23F) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. Costumo confirmar as informações que recebo pela Internet antes de compartilhar com outras pessoas "
label var P2307 "P.23G) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. Se recebo uma informação de pessoas conhecidas não vejo necessidade de confirmar "
label var P26 "P.26) Quantas pessoas moram neste domicílio, excluindo o(a) sr(a)? (Espontânea) "
label var P2701 "P.27A) Dessas pessoas que moram com o(a) sr(a), excluindo o(a) sr(a), quantas delas têm até 2 anos? "
label var P2702 "P.27B) Dessas pessoas que moram com o(a) sr(a), excluindo o(a) sr(a), quantas delas têm de 3 a 6 anos? "
label var P2703 "P.27C) Dessas pessoas que moram com o(a) sr(a), excluindo o(a) sr(a), quantas delas têm de 7 a 10 anos? "
label var P2704 "P.27D) Dessas pessoas que moram com o(a) sr(a), excluindo o(a) sr(a), quantas delas têm de 11 a 14 anos? "
label var P2705 "P.27E) Dessas pessoas que moram com o(a) sr(a), excluindo o(a) sr(a), quantas delas têm de 15 a 17 anos? "
label var P2706 "P.27F) Dessas pessoas que moram com o(a) sr(a), excluindo o(a) sr(a), quantas delas têm de 18 a 29 anos? "
label var P2707 "P.27G) Dessas pessoas que moram com o(a) sr(a), excluindo o(a) sr(a), quantas delas têm de 30 a 64 anos? "
label var P2708 "P.27H) Dessas pessoas que moram com o(a) sr(a), excluindo o(a) sr(a), quantas delas têm 65 anos ou mais? "
label var P2801 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2802 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2803 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2804 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2805 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2806 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2807 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2808 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2809 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2810 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2811 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2812 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2813 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P2814 "P.28) Quem são estas pessoas? Qual a relação de parentesco delas em relação ao(à) sr(a)? (Espontânea) "
label var P29 "P.29) Qual dessas pessoas é o chefe da família? (Espontânea) "
label var P30 "P.30) Quem é responsável pelas decisões financeiras na sua casa? (Espontânea) "
label var P31 "P.31) O(A) sr(a) tem filhos? (Espontânea) "
label var P31A01 "P.31A.1) O(s) seu(s) filho(s) têm de 0 a 5 anos? "
label var P31A02 "P.31A.2) O(s) seu(s) filho(s) têm de 6 a 17 anos? "
label var P31A03 "P.31A.3) O(s) seu(s) filho(s) têm de 18 anos ou mais? "
label var P32 "P.32) Qual era sua idade quando teve o(a) seu o(a) primeiro(a) filho(a)? (Espontânea) "
label var P3301 "P.33A) O(A) sr(a) faz ou já fez algum destes cursos? Idiomas "
label var P3302 "P.33B) O(A) sr(a) faz ou já fez algum destes cursos? Informática "
label var P3303 "P.33C) O(A) sr(a) faz ou já fez algum destes cursos? Capacitação profissional / Curso profissionalizante "
label var P3304 "P.33D) O(A) sr(a) faz ou já fez algum destes cursos? Treinamentos técnicos para aperfeiçoamento das atividades de minha função "
label var P3305 "P.33E) O(A) sr(a) faz ou já fez algum destes cursos? Treinamentos de atualização (incorporação de novos equipamentos, sistemas, práticas etc.) "
label var P3306 "P.33F) O(A) sr(a) faz ou já fez algum destes cursos? Treinamentos comportamentais (ex.: gestão do tempo, liderança, trabalho em equipe etc.) "
label var P3307 "P.33G) O(A) sr(a) faz ou já fez algum destes cursos? Cursos por hobby ou lazer (ex.: artes, cultura, história, filosofia, culinária, artesanato etc.) "
label var P3308 "P.33H) O(A) sr(a) faz ou já fez algum destes cursos? Curso preparatório para vestibular "
label var P3309 "P.33I) O(A) sr(a) faz ou já fez algum destes cursos? Curso preparatório para concurso público "
label var P3310 "P.33J) O(A) sr(a) faz ou já fez algum destes cursos? Outros "
label var p3310_out "P.33) Outros "
label var P33A01 "P.33A.1) O(A) sr(a) está fazendo ou fez o curso presencial ou à distância de idiomas nos últimos doze meses? "
label var P33A02 "P.33A.2) O(A) sr(a) está fazendo ou fez o curso presencial ou à distância de informática nos últimos doze meses? "
label var P33A03 "P.33A.3) O(A) sr(a) está fazendo ou fez o curso presencial ou à distância de capacitação profissional / curso profissionalizante nos últimos doze meses? "
label var P33A04 "P.33A.4) O(A) sr(a) está fazendo ou fez o curso presencial ou à distância de treinamentos técnicos para aperfeiçoamento das atividades de minha função nos últimos doze meses? "
label var P33A05 "P.33A.5) O(A) sr(a) está fazendo ou fez o curso presencial ou à distância de treinamentos de atualização (incorporação de novos equipamentos, sistemas, práticas etc.) nos últimos doze meses? "
label var P33A06 "P.33A.6) O(A) sr(a) está fazendo ou fez o curso presencial ou à distância de treinamentos comportamentais (ex.: gestão do tempo, liderança, trabalho em equipe etc.) nos últimos doze meses? "
label var P33A07 "P.33A.7) O(A) sr(a) está fazendo ou fez o curso presencial ou à distância de cursos por hobby ou lazer (ex.: artes, cultura, história, filosofia, culinária, artesanato etc.) nos últimos doze meses? "
label var P33A08 "P.33A.8) O(A) sr(a) está fazendo ou fez o curso presencial ou à distância de curso preparatório para vestibular nos últimos doze meses? "
label var P33A09 "P.33A.9) O(A) sr(a) está fazendo ou fez o curso presencial ou à distância de curso preparatório para concurso público nos últimos doze meses? "
label var P33A10 "P.33A.10) O(A) sr(a) está fazendo ou fez outros cursos presencial ou à distância nos últimos doze meses? "
label var P3401 "P.34A) Quem pagou a maior parte ou todo o curso de idiomas? "
label var P3402 "P.34B) Quem pagou a maior parte ou todo o curso de informática? "
label var P3403 "P.34C) Quem pagou a maior parte ou todo o curso de capacitação profissional / curso profissionalizante? "
label var P3404 "P.34D) Quem pagou a maior parte ou todo o curso de treinamentos técnicos para aperfeiçoamento das atividades de minha função? "
label var P3405 "P.34E) Quem pagou a maior parte ou todo o curso de treinamentos de atualização (incorporação de novos equipamentos, sistemas, práticas etc.)? "
label var P3406 "P.34F) Quem pagou a maior parte ou todo o curso de treinamentos comportamentais (ex.: gestão do tempo, liderança, trabalho em equipe etc.)? "
label var P3407 "P.34G) Quem pagou a maior parte ou todo o cursos por hobby ou lazer (ex.: artes, cultura, história, filosofia, culinária, artesanato etc.)? "
label var P3408 "P.34H) Quem pagou a maior parte ou todo o curso preparatório para vestibular? "
label var P3409 "P.34I) Quem pagou a maior parte ou todo o curso preparatório para concurso público? "
label var P3410 "P.34J) Quem pagou a maior parte ou todos os outros cursos? "
label var P3601 "P.36A) Qual o seu grau de dificuldade para realizar cada uma das tarefas? Preparar uma lista do que precisa comprar "
label var P3602 "P.36B) Qual o seu grau de dificuldade para realizar cada uma das tarefas? Verificar a data de vencimento dos produtos que compra "
label var P3603 "P.36C) Qual o seu grau de dificuldade para realizar cada uma das tarefas? Conferir o consumo de água ou luz ou telefone "
label var P3604 "P.36D) Qual o seu grau de dificuldade para realizar cada uma das tarefas? Ver a temperatura no termômetro "
label var P3605 "P.36E) Qual o seu grau de dificuldade para realizar cada uma das tarefas? Conferir troco "
label var P3606 "P.36F) Qual o seu grau de dificuldade para realizar cada uma das tarefas? Realizar depósito ou saques em caixas eletrônicos "
label var P3607 "P.36G) Qual o seu grau de dificuldade para realizar cada uma das tarefas? Entender gráficos e tabelas inseridos em matérias de jornais, revistas, etc "
label var P3608 "P.36H) Qual o seu grau de dificuldade para realizar cada uma das tarefas? Escrever mensagem em celular SMS, etc "
label var P3801 "P.38A) O(A) sr(a) pertence e participa ativamente, pertence e não participa ativamente, pertencia no passado, mas hoje não pertence mais, ou nunca pertenceu a cada organização: ONG/ Entidade Social "
label var P3802 "P.38B) O(A) sr(a) pertence e participa ativamente, pertence e não participa ativamente, pertencia no passado, mas hoje não pertence mais, ou nunca pertenceu a cada organização: Sindicato, associação profissional ou empresarial "
label var P3803 "P.38C) O(A) sr(a) pertence e participa ativamente, pertence e não participa ativamente, pertencia no passado, mas hoje não pertence mais, ou nunca pertenceu a cada organização: Organização religiosa ou de igreja "
label var P3804 "P.38D) O(A) sr(a) pertence e participa ativamente, pertence e não participa ativamente, pertencia no passado, mas hoje não pertence mais, ou nunca pertenceu a cada organização: Organização de esportes, lazer ou cultural "
label var P3805 "P.38E) O(A) sr(a) pertence e participa ativamente, pertence e não participa ativamente, pertencia no passado, mas hoje não pertence mais, ou nunca pertenceu a cada organização: Partidos Políticos "
label var P3806 "P.38F) O(A) sr(a) pertence e participa ativamente, pertence e não participa ativamente, pertencia no passado, mas hoje não pertence mais, ou nunca pertenceu a cada organização: Organização estudantil "
label var P3807 "P.38G) O(A) sr(a) pertence e participa ativamente, pertence e não participa ativamente, pertencia no passado, mas hoje não pertence mais, ou nunca pertenceu a cada organização: Associação ou comunidade de bairro "
label var P3808 "P.38H) O(A) sr(a) pertence e participa ativamente, pertence e não participa ativamente, pertencia no passado, mas hoje não pertence mais, ou nunca pertenceu a cada organização: Associação artística/ cultural "
label var P3809 "P.38I) O(A) sr(a) pertence e participa ativamente, pertence e não participa ativamente, pertencia no passado, mas hoje não pertence mais, ou nunca pertenceu a cada organização: Associação ambientalista "
label var P39 "P.39) Qual destas é a sua situação atual de trabalho? "
label var P40 "P.40) Há quanto tempo o(a) sr(a) está nesta situação atual? (Espontânea) "
label var P41 "P.41) O(A) sr(a) já trabalhou anteriormente? "
label var P41_B "P.41B) O(A) sr(a) já trabalhou anteriormente? "
label var P42 "P.42) Qual o ramo de atividade em que o(a) sr(a) trabalha ou trabalhou? (Espontânea) "
label var P44 "P.44) O(A) sr(a) trabalha ou trabalhou: "
label var P45 "P.45) Qual é o cargo que o(a) sr(a) ocupa no trabalho ou ocupou no último trabalho? "
label var P45B "P.45B) O(A) sr(a) trabalha ou trabalhava? "
label var P45C "P.45C) O(A) sr(a) tem carteira assinada? "
label var P46 "P.46) Qual função o(a) sr(a). exerce no trabalho atual? (Espontânea) "
label var P46_Sintese "P.46) Qual função o(a) sr(a). exerce no trabalho atual? (Espontânea) "
label var P47_ANOS "P.47) Há quanto tempo o(a) sr(a) exerce a sua função atual? Anos "
label var P47_MESES "P.47) Há quanto tempo o(a) sr(a) exerce a sua função atual? Meses "
label var P48 "P.48) Quantas horas por semana o(a) sr(a) trabalha ou trabalhava? "
label var P4901 "P.49) Destes equipamentos, quais o(a) sr(a) utiliza ou utilizava para o trabalho? "
label var P4902 "P.49) Destes equipamentos, quais o(a) sr(a) utiliza ou utilizava para o trabalho? "
label var P4903 "P.49) Destes equipamentos, quais o(a) sr(a) utiliza ou utilizava para o trabalho? "
label var P4904 "P.49) Destes equipamentos, quais o(a) sr(a) utiliza ou utilizava para o trabalho? "
label var P4905 "P.49) Destes equipamentos, quais o(a) sr(a) utiliza ou utilizava para o trabalho? "
label var P4906 "P.49) Destes equipamentos, quais o(a) sr(a) utiliza ou utilizava para o trabalho? "
label var P4907 "P.49) Destes equipamentos, quais o(a) sr(a) utiliza ou utilizava para o trabalho? "
label var P5001 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5002 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5003 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5004 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5005 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5006 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5007 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5008 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5009 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5010 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5011 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5012 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5013 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5014 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5015 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5016 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5017 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5018 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5019 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5020 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5021 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5022 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5023 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5024 "P.50) Para realizar suas atividades de trabalho, o sr(a) lê ou lia? "
label var P5101 "P.51) Para realizar suas atividades de trabalho, o(a) sr(a) usa ou usava? "
label var P5102 "P.51) Para realizar suas atividades de trabalho, o(a) sr(a) usa ou usava? "
label var P5103 "P.51) Para realizar suas atividades de trabalho, o(a) sr(a) usa ou usava? "
label var P5104 "P.51) Para realizar suas atividades de trabalho, o(a) sr(a) usa ou usava? "
label var P5105 "P.51) Para realizar suas atividades de trabalho, o(a) sr(a) usa ou usava? "
label var P5106 "P.51) Para realizar suas atividades de trabalho, o(a) sr(a) usa ou usava? "
label var P5201 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5202 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5203 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5204 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5205 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5206 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5207 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5208 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5209 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5210 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5211 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5212 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5213 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5214 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5215 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5216 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5217 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P5218 "P.52) No seu trabalho atual ou anterior, o(a) sr(a) escreve ou escrevia? "
label var P53 "P.53) Antes do seu trabalho atual, o(a) sr(a) exerceu alguma função diferente por cinco anos ou mais? (Espontânea) "
label var P53A "P.53A) E qual função o(a) sr(a). exercia? (Espontânea) "
label var P5401 "P.54A) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. Eu me sinto bastante satisfeito com meu trabalho atual "
label var P5402 "P.54B) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. Na maioria dos dias eu me sinto entusiasmado com meu trabalho "
label var P5403 "P.54C) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. Cada dia de trabalho parece interminável "
label var P5404 "P.54D) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. Eu encontro prazer de verdade no meu trabalho "
label var P5405 "P.54E) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. Eu considero meu trabalho muito desagradável "
label var P5406 "P.54F) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. Eu estou satisfeito com o sucesso alcançado em minha carreira "
label var P5407 "P.54G) Destas frases, gostaria que o(a) sr(a) dissesse quanto o(a) sr(a) concorda ou discorda de cada uma delas. Eu estou satisfeito com o progresso que tenho feito para atingir os meus objetivos de carreira "
label var P5501 "P.55A) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Operar máquinas para usinagem de peças "
label var P5502 "P.55B) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Cantar em um coral "
label var P5503 "P.55C) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Estar disponível para ajudar as pessoas "
label var P5504 "P.55D) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Negociar com clientes "
label var P5505 "P.55E) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Analisar os cenários econômicos nacional e internacional "
label var P5506 "P.55F) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Apresentar números artísticos para uma plateia "
label var P5507 "P.55G) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Participar de planejamentos estratégicos em empresas "
label var P5508 "P.55H) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Fazer análises e experimentos em laboratórios "
label var P5509 "P.55I) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Executar manutenções em máquinas e equipamentos "
label var P5510 "P.55J) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Coordenar o desempenho de equipes de trabalho "
label var P5511 "P.55K) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Oferecer orientação às pessoas, grupos ou população sobre saúde e bem-estar "
label var P5512 "P.55L) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Fiscalizar o cumprimento de leis "
label var P5513 "P.55M) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Explicar fenômenos físicos da natureza "
label var P5514 "P.55N) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Participar da criação de cenários teatrais "
label var P5515 "P.55O) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Prestar serviços sociais em comunidades e bairros "
label var P5516 "P.55P) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Calcular a área de figuras geométricas "
label var P5517 "P.55Q) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Arquivar documentos e notas importantes "
label var P5518 "P.55R) Desta lista com várias atividades, gostaria de saber o seu grau de interesse em fazer cada uma delas. Ler artigos e livros científicos "
label var P57 "P.57) Qual a sua religião? (Espontânea) "
label var P58 "P.58) Vou fazer uma pergunta exatamente como é feita pelo IBGE para classificação da população brasileira. A sua cor ou raça é: "
label var AUTO "Quantidade de automóveis de passeio exclusivamente para uso particular "
label var EMPREG "Quantidade de empregados mensalistas, considerando apenas os que trabalham pelo menos cinco dias por semana "
label var MAQ "Quantidade de máquinas de lavar roupa, excluindo tanquinho "
label var BANH "Quantidade de banheiros "
label var GELAD "Quantidade de geladeiras "
label var FREEZER "Quantidade de freezers independentes ou parte da geladeira duplex "
label var PC "Quantidade de microcomputadores, considerando computadores de mesa, laptops, notebooks e netbooks e desconsiderando tablets, palms ou smartphones "
label var LAVA_LOUCA "Quantidade de lavadora de louças "
label var MICROONDAS "Quantidade de fornos de micro-ondas, incluindo os aparelhos com dupla função (de micro-ondas e forno elétrico) "
label var MOTO "Quantidade de motocicletas, desconsiderando as usadas exclusivamente para uso profissional. "
label var SECADORA "Quantidade de máquinas secadoras de roupas, considerando lava-e-seca. "
label var TV "Quantidade de TVs "
label var RADIO "Quantidade de Rádios "
label var VIDEO "Quantidade de Vídeos "
label var DVD "Quantidade de DVDs "
label var PCE3 "A água utilizada nesse domicílio é proveniente de: "
label var PCE4 "Considerando o trecho da rua do seu domicílio, você diria que a rua é: "
label var INSTCH2 "Escolaridade chefe "
label var ClasseSocial_2008_Pontos "<none> "
label var ClasseSocial_2008 "<none> "
label var ClasseSocial_2015_Pontos "<none> "
label var Classe_2015 "CRITÉRIO ECONÔMICO BRASIL "
label var REND1 "RENDA1) Em qual destas faixas está a sua renda individual do mês passado? "
label var REND2 "RENDA2) Em qual destas faixas está a renda total da sua família no mês passado, somando as rendas de todas as pessoas que moram com o(a) sr(a), inclusive a sua? "
label var REND3 "RENDA3) Em valores reais, quanto o(a) sr(a) recebeu, pessoalmente, no último mês? "
label var CODIGO "IDENTIFICAÇÃO DO QUESTIONÁRIO "
label var setor "SITUAÇÃO DO SETOR "
label var classe "CRITÉRIO ECONÔMICO BRASIL "
label var instcr "ESCOLARIDADE "
label var instru "ESCOLARIDADE "
label var rendcr "RENDA FAMILIAR (EM SALÁRIOS MÍNIMOS) "
label var rendper "RENDA FAMILIAR (EM SALÁRIOS MÍNIMOS) "
label var rend_indiv "RENDA PESSOAL (EM SALÁRIOS MÍNIMOS) "
label var inst_per "ANOS DE ESTUDO "
label var cond "CONDIÇÃO DO MUNICÍPIO "
label var porte "PORTE DO MUNICÍPIO (EM NÚMERO DE HABITANTES) "
label var portecr "PORTE DO MUNICÍPIO (EM NÚMERO DE HABITANTES) "
label var portecrx "PORTE DO MUNICÍPIO (EM NÚMERO DE HABITANTES) "
label var reg "REGIÃO "
label var regx "REGIÃO "
label var EST "ESTADO "
label var cod_muni "MUNICÍPIO "
label var ProfAlfab "Valor de Proficiência Combinada "
label var InafAlfab "Grupos de Analfabetismo (Prova Combinada) "
label var InafAlfab5n "Grupos de Analfabetismo (Prova Combinada) 5 grupos "
